name: CI
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/deploy-pages@v4      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
